#!/usr/bin/env bash
# use a while loop to print the vname 10 times
vname="Best School"
count=0

while [ "$count" -lt 11 ]; do
	if [ "$count" = 9 ]; then
		echo "HI"
        else 
		echo "$vname"
        fi
	count=$((count + 1))
done
