#!/usr/bin/env bash

# Use a while loop to chek if 4 bad luck if 8 good luck
vname="Best School"
count=1

while [ "$count" -lt 11 ]; do
	if [ "$count" = 4 ]; then
		echo "bad luck"
	elif [ "$count" = 8 ]; then
		echo "good luck"
	else
		echo "$vname"
	fi
	count=$((count + 1))
done
